#!/bin/ruby

# (arm-pkg Application File) => HelloWorld.0.1.src.arm

# ** Long syntax ** #
# arm-pkg install HelloWorld.0.1.amd64
# arm-pkg uninstall HelloWorld.0.1.amd64


# ~ Don't ask for confirmation ~ #
# arm-pkg install-confirm HelloWorld.0.1.amd64
# arm-pkg uninstall-confirm HelloWorld.0.1.amd64



# ** Short syntax ** #
# arm-pkg -i HelloWorld.0.1.amd64
# arm-pkg -u HelloWorld.0.1.amd64

# ~ Don't ask for confirmation ~ #
# arm-pkg -ic HelloWorld.0.1.amd64
# arm-pkg -uc HelloWorld.0.1.amd64




# (Sources folder/directory) => HelloWorld.0.1.amd64
# ~ Don't ask for confirmation ~ #

# ** Long syntax ** #
# arm-pkg generate-arm HelloWorld.0.1.amd64


# ** Short syntax ** #
# arm-pkg -gen HelloWorld.0.1.amd64




# (DEB Application File) => helloworld_0.1_amd64.deb

# ** Long syntax ** #
# sudo alien --to-rpm helloworld_0.1_amd64.deb
# arm-pkg install hello-world-0.1.amd64.rpm --redhat


# ** Short syntax ** #
# sudo alien -r helloworld_0.1_amd64.deb
# arm-pkg install hello-world-0.1.amd64.rpm --redhat




# (RPM Application File) => hello-world-0.1.amd64.rpm

# ** Long syntax ** #
# arm-pkg install hello-world-0.1.amd64.rpm --redhat
# arm-pkg uninstall hello-world-0.1.amd64.rpm --redhat


# ~ Don't ask for confirmation ~ #
# arm-pkg install-confirm hello-world-0.1.amd64.rpm --redhat
# arm-pkg uninstall-confirm hello-world-0.1.amd64.rpm --redhat



# ** Short syntax ** #
# arm-pkg -i hello-world-0.1.amd64.rpm --redhat
# arm-pkg -u hello-world-0.1.amd64.rpm --redhat

# ~ Don't ask for confirmation ~ #
# arm-pkg -ic hello-world-0.1.amd64.rpm --redhat
# arm-pkg -uc hello-world-0.1.amd64.rpm --redhat

SOURCE_EXTENSION=".src"
EXTENSION=".arm"
ARM_PKG_EXTENSION=".src.arm"
TOOL="arm-src"

if ARGV[0] == "-gen" or ARGV[0] == "generate-arm"
    system("tar -czf #{ARGV[1]}#{EXTENSION} #{ARGV[1]}")

elsif ARGV[0] == "-src" or ARGV[0] == "new-source"
    system("cp -Rf /bin/arm-source/HelloWorld.0.1.src #{ARGV[1]}")

    
# Issue here when installing
elsif ARGV[0] == "-i" or ARGV[0] == "install"
    # arm-pkg Package Manager
    system("tar -xzf #{ARGV[1]}#{EXTENSION} && cd #{ARGV[1]} && sudo ./arm install")


elsif ARGV[0] == "-u" or ARGV[0] == "uninstall" or ARGV[1] == "remove"
    # arm-pkg Package Manager
    system("tar -xzf #{ARGV[1]}#{EXTENSION} && cd #{ARGV[1]} && sudo ./arm uninstall")


elsif ARGV[0] == "-ic" or ARGV[0] == "install-confirm"
    system("tar -xzf #{ARGV[1]}#{EXTENSION} && cd #{ARGV[1]} && sudo ./arm install-confirm")


elsif ARGV[0] == "-uc" or ARGV[0] == "uninstall-confirm"
    system("tar -xzf #{ARGV[1]}#{EXTENSION} && cd #{ARGV[1]} && sudo ./arm uninstall-confirm")


else#if ARGV[0] == "help"
    # Help
	puts("---------------------------------------------------------\n\n")

    puts("**Manual page (Manpage)**")
    puts("#{TOOL} help\n\n")

    puts("**References**")
    puts("<package> => HelloWorld.1.0.src")
    puts("<file>   =>  HelloWorld.1.0.src.arm\n\n")
    
    puts("---------------------------------------------------------\n\n")

    puts("**Long syntax**\n\n")
    
    puts(" ~ Install and Uninstall packages (#{TOOL}) ~")
    puts("#{TOOL} install <package>")
    puts("#{TOOL} uninstall <package>\n\n")
    
    puts(" ~ Don't ask for confirmation (#{TOOL}) ~ ")
    puts("#{TOOL} install-confirm <package>")
    puts("#{TOOL} uninstall-confirm <package>\n\n")
    
    puts(" ~ Compress [#{ARM_PKG_EXTENSION}] package (#{TOOL}) ~")
    puts("#{TOOL} generate-arm <package>\n\n")

    puts(" ~ Generate new [#{ARM_PKG_EXTENSION}] source package (#{TOOL}) ~ ")
    puts("#{TOOL} new-source <package_name>\n\n")

    puts("---------------------------------------------------------\n\n")

    puts("**Short syntax**")

    puts(" ~ Install and Uninstall packages (#{TOOL}) ~ ")
    puts("#{TOOL} -i <package>")
    puts("#{TOOL} -u <package>\n\n")
    
    puts(" ~ Don't ask for confirmation (#{TOOL}) ~ ")
    puts("#{TOOL} -ic <package>")
    puts("#{TOOL} -uc <package>\n\n\n")
    

    puts(" ~ Compress [#{ARM_PKG_EXTENSION}] package (#{TOOL}) ~ ")
    puts("#{TOOL} -gen <package>\n\n")

    puts(" ~ Generate new [#{ARM_PKG_EXTENSION}] source package (#{TOOL}) ~ ")
    puts("#{TOOL} -src <package>\n\n")
    

    puts("---------------------------------------------------------\n\n")
    

    puts("**Examples**")
    puts("HelloWorld.0.1#{SOURCE_EXTENSION} => #{TOOL} (package reference)")
    puts("HelloWorld.0.1#{SOURCE_EXTENSION}#{EXTENSION} => #{TOOL} (package file)\n\n")
    
    puts("**Short syntax**")
    puts("#{TOOL} -i HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} -u HelloWorld.0.1#{SOURCE_EXTENSION}\n")
    
    puts("#{TOOL} -ic HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} -uc HelloWorld.0.1#{SOURCE_EXTENSION}\n")
    
    puts("#{TOOL} -gen HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} -src HelloWorld.0.1#{SOURCE_EXTENSION}\n\n")
    

    puts("**Long syntax**")
    puts("#{TOOL} install HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} uninstall HelloWorld.0.1#{SOURCE_EXTENSION}\n")
    
    puts("#{TOOL} install-confirm HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} uninstall-confirm HelloWorld.0.1#{SOURCE_EXTENSION}\n")
    
    puts("#{TOOL} generate-arm HelloWorld.0.1#{SOURCE_EXTENSION}")
    puts("#{TOOL} new-source HelloWorld.0.1#{SOURCE_EXTENSION}\n\n\n")
    
    puts("---------------------------------------------------------\n\n\n")
end